import { Prompt } from "next/font/google";
import "@/app/globals.css";
import Navigation from "@/components/Navigation";
import Footersection from "@/components/Footersection"; 
const prompt = Prompt({
  subsets: ["thai", "latin"],
  weight: ["300"],
  variable: "--font-prompt",
});

export const metadata = {
  title: "เว็บจองห้องพัก",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="th" 
      className={`${prompt.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans">
        <Navigation />
        
        {/* 🛠️ 2. ย้าย {children} (เนื้อหาหลัก) มาไว้ตรงกลาง */}
        {children}
        
        {/* 🛠️ 3. ย้าย Footersection ไปไว้ล่างสุดของเว็บ */}
        <Footersection />
        
      </body>
    </html>
  );
}